<a href="https://colab.research.google.com/github/audomsak-pypy/PythonDataViz2026/blob/main/HW7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *HW7* 673020271-0 #

##สร้างตารางใหม่ ที่ค่าใน ```sex``` เป็น missing ทั้งหมด  
* สรุปว่าทำไม record นั้นๆถึงเป็น missing

###ดึงข้อมูลมาใช้

In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
path = "/content/drive/MyDrive/DataViz_2026"
covid_file = os.path.join(path,'confirmed-cases.csv')
print(covid_file)

/content/drive/MyDrive/DataViz_2026/confirmed-cases.csv

In [ ]:
data = pd.read_csv(covid_file)
data.head()

/tmp/ipykernel_4318/3129093645.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(covid_file)

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

###สร้างเป็นตารางใหม่ ที่ข้อมูลเพศเป็นค่า  NaN

In [ ]:
missing_sex = data[pd.isnull(data["sex"])]
missing_sex

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
4397,4398,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4398,4399,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4399,4400,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4400,4401,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4401,4402,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
...,...,...,...,...,...,...,...,...,...,...,...
838332,838333,12/8/2021,11/8/2021,NaN,3.0,ปี,Thailand,กรุงเทพมหานคร,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,กรุงเทพมหานคร,บางคอแหลม
839174,839175,12/8/2021,11/8/2021,NaN,47.0,ปี,Thailand,กรุงเทพมหานคร,ระบุไม่ได้,กรุงเทพมหานคร,บางคอแหลม
839304,839305,12/8/2021,11/8/2021,NaN,NaN,NaN,NaN,กรุงเทพมหานคร,ระบุไม่ได้,NaN,NaN
839396,839397,12/8/2021,11/8/2021,NaN,NaN,NaN,NaN,นครราชสีมา,ทัณฑสถาน/เรือนจำ,นครราชสีมา,NaN
839397,839398,12/8/2021,11/8/2021,NaN,NaN,NaN,NaN,นครราชสีมา,ทัณฑสถาน/เรือนจำ,นครราชสีมา,NaN

**สรุปได้ว่า:** ข้อมูลที่ missing อาจเกิดจากการเก็บข้อมูลที่ไม่ครบถ้วน การกอกข้อมูลมีข้อผิดพลาด กรอกข้อมูลตกหล่น

###ใช้คำสั่ง groupby

In [ ]:
missing_sex.groupby('province_of_isolation').describe()

                           No.                                          \
                         count           mean            std       min
province_of_isolation
กระบี่                    41.0  287891.219512  280151.884354   73912.0
กรุงเทพมหานคร          28651.0  469521.853513  223068.078638   27020.0
กาญจนบุรี                 51.0  643335.431373   54302.146198  266188.0
กาฬสินธุ์                872.0  710240.678899   81120.413355  433142.0
ขอนแก่น                    3.0  651686.000000       1.000000  651685.0
...                        ...            ...            ...       ...
เชียงใหม่               4781.0  100547.203932   25241.829552   31491.0
เพชรบุรี                 642.0  171883.331776   68898.937903  133092.0
เพชรบูรณ์                987.0  657061.115502   75110.144128  497929.0
เลย                       50.0  438586.720000  109075.917561  322193.0
แพร่                      32.0  577185.093750  160814.183347   57932.0


                             25%       50%        75%       max
province_of_isolation
กระบี่                  73924.00   73935.0  591512.00  790309.0
กรุงเทพมหานคร          315466.50  478695.0  668646.50  839305.0
กาญจนบุรี              651844.50  651857.0  651869.50  651882.0
กาฬสินธุ์              704954.75  705172.5  748680.25  804129.0
ขอนแก่น                651685.50  651686.0  651686.50  651687.0
...                          ...       ...        ...       ...
เชียงใหม่              102137.00  103332.0  104527.00  168360.0
เพชรบุรี               141777.25  141937.5  155543.75  501882.0
เพชรบูรณ์              615771.50  673193.0  737265.50  757291.0
เลย                    322205.25  421348.5  421360.75  625897.0
แพร่                   512846.75  512854.5  678499.00  817167.0

[69 rows x 8 columns]